package labbios.db;

import java.util.Date;

public class PacienteTemporario {
	private int PACIENTE_TEMPORARIO_ID;
	private String PACIENTE_TEMPORARIO_NOME;
	private Date PACIENTE_TEMPORARIO_DT_NASCIMENTO;
	private char PACIENTE_TEMPORARIO_SEXO;
	private String PACIENTE_TEMPORARIO_OBS;
	
	public int getPACIENTE_TEMPORARIO_ID() {
		return PACIENTE_TEMPORARIO_ID;
	}
	public void setPACIENTE_TEMPORARIO_ID(int pACIENTE_TEMPORARIO_ID) {
		PACIENTE_TEMPORARIO_ID = pACIENTE_TEMPORARIO_ID;
	}
	public String getPACIENTE_TEMPORARIO_NOME() {
		return PACIENTE_TEMPORARIO_NOME;
	}
	public void setPACIENTE_TEMPORARIO_NOME(String pACIENTE_TEMPORARIO_NOME) {
		PACIENTE_TEMPORARIO_NOME = pACIENTE_TEMPORARIO_NOME;
	}
	public Date getPACIENTE_TEMPORARIO_DT_NASCIMENTO() {
		return PACIENTE_TEMPORARIO_DT_NASCIMENTO;
	}
	public void setPACIENTE_TEMPORARIO_DT_NASCIMENTO(
			Date pACIENTE_TEMPORARIO_DT_NASCIMENTO) {
		PACIENTE_TEMPORARIO_DT_NASCIMENTO = pACIENTE_TEMPORARIO_DT_NASCIMENTO;
	}
	public char getPACIENTE_TEMPORARIO_SEXO() {
		return PACIENTE_TEMPORARIO_SEXO;
	}
	public void setPACIENTE_TEMPORARIO_SEXO(char pACIENTE_TEMPORARIO_SEXO) {
		PACIENTE_TEMPORARIO_SEXO = pACIENTE_TEMPORARIO_SEXO;
	}
	public String getPACIENTE_TEMPORARIO_OBS() {
		return PACIENTE_TEMPORARIO_OBS;
	}
	public void setPACIENTE_TEMPORARIO_OBS(String pACIENTE_TEMPORARIO_OBS) {
		PACIENTE_TEMPORARIO_OBS = pACIENTE_TEMPORARIO_OBS;
	}
	
	

}
